### ISSUE TITLE
[5장][글로벌 락 사용 시 주의 사항]

### ISSUE THREAD

**Issue by sdsd988** [somefood/cs-study#43]
> p.[161] 글로벌 락 주의

질문 : FLUSH TABLES WITH READ LOCK 명령 실행 전 **쓰기 잠금**을 거는 SQL이 실행됐을 경우, 왜 **읽기 잠금**을 걸기 위해 먼저 실행된  SQL이 완료되고 그 트랜잭션이 완료될 때까지 기다려야 한다는 걸까요? 

- 읽기 잠금 - 쓰기 잠금 - 글로벌 락 순서로 진행되다고 간주하면 될까요?

**Comment by somefood** [comment]
FLUSH TABLES WITH READ LOCK 같은 글로벌 락을 거는 이유는 테이블 백업 or 복제를 수행하는데 사용한다고 합니다.
앞에 걸려 있는 SQL이나 그 트랜잭션이 완료될 때까지 기다려야 하는 이유는 데이터 정합성을 맞추기 위해서라 보시면 됩니다.
가령 내가 A라는 레코드를 수정 작업 중인데, 이 상태에서 락을 걸어버리고 복제를 해버린다 치면 A에 대한 값이 이전걸로 복제가 되었고, 이는 일관성이 깨진다고 보면 됩니다. 그렇기 때문에 앞에 있던 작업을 처리를 먼저한다고 보면 좋을거 같습니다.

근데 본문에 InnoDB같은 경우에는 트랜잭션을 지원하기 때문에 이제는 잘 안쓰일거 같은 느낌이 드네요!
