### ISSUE TITLE
[5장] FLUSH가 정확히 뭔지 알고 싶습니다

### ISSUE THREAD

**Issue by denmark-dangnagui** [somefood/cs-study#44]
> p.[161] 글로벌 락
질문 : 글로벌 락을 FLUSH TABLE WITH READ LOCK 명령으로 획득할 수 있다는데, FLUSH가 무엇인지 알고 싶은데 정확히 FLUSH가 테이블을 어떻게 한다는 것인지 알고 싶습니다

**Comment by somefood** [comment]
[공식문서](https://dev.mysql.com/doc/refman/8.0/en/flush.html#flush-tables-with-read-lock)에 따르면
FLUSH 명령어는 다양한 내부 캐시를 지우거나 다시 로드하는 역할을 하고, 또는 잠금을 획들할 수 있도록 해주는 구문이라 보면 됩니다.

플러시의 의미는 캐시나 버퍼 등에 저장된 데이터를 비운다라고 보면 될거 같고,
FLUSH TABLE WITH READ LOCK 같은 거는 읽기 잠금을 걸겠다는 특별한 구문이지 않을까 싶네요.
