### ISSUE TITLE
[5장] 개발자가 잠금을 사용할 때

### ISSUE THREAD

**Issue by denmark-dangnagui** [somefood/cs-study#45]
> p.[5장 잠금]

질문 : 잠금의 범주나 영향은 알 것 같은데, 개발을 하면서 '잠금' 기능(?) 을 직접 코드를 치면서 적용할 경우가 있는지 있다면 언제 그런 경우인지 궁금합니다.

**Comment by somefood** [comment]
락은 트랜잭션이 걸려있는 경우 다른 트랜잭션에서 수정하지 못하게끔 막아주는 동시성 제어라고 보시면 됩니다.
저도 아직 뚜렷한 경험이 없어 말하긴 어렵지만, 강의에서 본 내용 토대로 설명 드리면 아래와 같습니다.
![image](https://user-images.githubusercontent.com/24751937/228594072-f9b27ef6-b8e8-44ed-a82e-4fdae1ce6aa3.png)

가령 배치 서비스를 돌리면서 특정 칼럼을 활용하는데, 이때 아무 누구도 이 칼럼의 값을 건들지 못하도록 락을 걸어버릴 수도 있겠네요.
