### ISSUE TITLE
[5장] 네임드 락﻿ 사용시 데드락

### ISSUE THREAD

**Issue by denmark-dangnagui** [somefood/cs-study#46]
> p.[163장]  네임드 락 사용시 데드락

질문 : '배치 프로그램에서 한꺼번에 많은 레코드를 변경하는 쿼리는 자주 데드락의 원인이 된다.'  이런 말이 있는데 데드락이 정확히 어느 상황에서 걸리는지 정확히 왜 대량 레코드를 변경할 때 데드락이 걸리는지 정확히 이해가 안되는데 이해한 걸 공유해주시면 좋을 것 같습니다.

**Comment by somefood** [comment]
가령 트랜잭션 A는 레코드 1, 2 순으로 대량 변경을 하고 있고, 트랜잭션 B는 2, 1 순으로 변경을 하고 있다고 칩시다.
A는 1을 수정하면서 B가 락걸어둔 2를 작업할 수 없어 대기를 해야하고, 반대로 B는 A의 작업을 기다리면서 서로 기다리게 되는게 데드락이라 보면 될거 같습니다.

이럴 때 네임드 락을 걸어서 락을 얻을 수 있을 거라 생각되는 시간을 지정해가지고 해결하는게 아닐까 싶습니다.
