### ISSUE TITLE
[8장 인덱스] 용어 질문

### ISSUE THREAD

**Issue by somefood** [somefood/cs-study#53]
> p.[252] 쿼리 주석 문

질문 : 범위 결정 조건과 체크 조건이라는 용어가 있던데 체크 조건 용어가 이해가 잘 안갑니다.
이 둘의 의미를 정확히 알고 싶습니다.

**Comment by denmark-dangnagui** [comment]
정의로 먼저 말씀드리자면
범위 결정 조건 : 작업의 범위를 결정하는 조건.
체크 조건 : 비교 작업의 범위를 줄이지 못하고 단순히 거름종이의 역할만 하는 조건. 
이렇게 볼 수 있습니다. 

- 케이스 A : INDEX(dept_no, emp_no)
- 케이스 B : INDEX(emp_no, dept_no)
위 케이스들을 예시로 두고 
SELECT * FROM dept_emp WHERE dept_no = 'd002' AND emp_no >= 10114;
이 쿼리를 사용한다고 한다면, 

케이스 A의 경우 먼저 dept_no = 'd002'를 찾고 그 다음 emp_no >= 10114 인 레코드를 찾습니다. 
이 과정에서 ept_no = ‘d002’ 아닌 인덱스가 아닐 때까지 읽는 방식으로 조회를 합니다.

반대로 반대로 케이스 B의 경우 먼저 emp_no >= 10114 찾고 그 다음 dept_no = 'd002' 인 레코드를 찾습니다.
이 과정에서 모든 레코드에 대해 dept_no = ‘d002’인지 비교하는 과정을 거쳐야 한다. 

이처럼, 범위 결정 조건의 경우 작업의 범위를 정해줄 수 있지만, 체크 조건의 경우 첫번째 칼럼에서 찾은 레코드들에
대해서 일일이 맞는지 확인을 거쳐야 하는 방식으로 진행됩니다.
이를 통해 인덱스 칼럼의 순서가 중요하다는 것을 알 수 있습니다.
