### ISSUE TITLE
[8장 인덱스] 리프 노드와 테이블 데이터 레코드

### ISSUE THREAD

**Issue by sdsd988** [somefood/cs-study#54]
> p.[222] 그림 8.6 B-Tree의 리프 노드와 테이블 데이터 레코드(InnoDB)

질문 : 그림 8.6의 프라이머리 키를 저장하고 있는 B-Tree와 테이블 데이터 레코드의 구조에 대해서 잘 이해가 가지 않습니다. 
두 구조의 차이와 관계에 대해서 설명해주세요.

**Comment by denmark-dangnagui** [comment]
제가 공부한 것으로 설명해보자면,
InnoDB 스토리지 엔진을 사용하는 테이블은 프라이머리키가 ROWID 역할을 합니다.
ROWID란, 테이블에서 행의 위치를 지정하는 논리적인 주소값입니다. 

그렇지만 이 주소값을 가지고 있다고 하더라도 InnoDB스토리지 엔진을 사용하는 테이블은 레코드를 읽을 때 데이터 파일로 바로 찾아갈 수 없습니다. InnoDB 스토리지 엔진에서 모든 세컨더리 인덱스 검색에서 데이터 레코드를 읽기 위해서는 반드시 프라이머리 키를 저장하고 있는 데이터 파일의 B-Tree를 다시 한번 검색을 하는 방식으로 조회를 합니다. 

그러한 이유는 InnoDB 스토리지 엔진 자체가 데이터 파일을 여러 개의 블록으로 나누어서 저장하고 각 블록을 페이지라는 단위로 관리한다는 것을 아실겁니다.  다시 본론으로 돌아와서 InnoDB 스토리지 엔진은 데이터 파일의 B-Tree 구조를 유지하기 위해 페이지들을 임의의 순서로 저장합니다. 그렇기에 또 한번 B-Tree 구조로 검색을 하는 것입니다.

이런 구조는 데이터의 무결성과 일관성을 보장하기 위해서입니다. InnoDB 스토리지 엔진은 트랜잭션과 롤백등을 지원하는데 이러한 기능을 구현하기 위해 데이터 파일의 구조가 항상 일정해야 하기 때문입니다. 결과적으로는 데이터 파일의 구조를 유지하기 위해 B-Tree로 추가 검색을 하는 것입니다.
