### ISSUE TITLE
[8장 인덱스] 인덱스 풀 스캔 질문

### ISSUE THREAD

**Issue by somefood** [somefood/cs-study#55]
> p.[234] 인덱스 풀 스캔은 인덱스 레인지 스캔보다 빠르지 않지만 테이블 풀 스캔보다 효율적이라고 한다.

질문 : 테이블 풀 스캔보다 효율적이며 테이블 자체의 크기보다 작으니 적은 디스크 I/O로 쿼리를 처리할 수 있다고 하는데 이부분이 이해가 잘 가지 않습니다. 만약 컬림 B가 인덱스가 걸려 있는데, 모든 B의 값이 동일한 경우 결국 다 찾는 행위가 될텐데, 이때도 효율적으로 처리가 될까요? 궁금합니다!

**Comment by denmark-dangnagui** [comment]
우선 차례차례 설명해드리겠습니다.
1. 인덱스 풀스탠이 테이블 풀 스캔보다 효율적이며 테이블 자체의 크기보다 작으니 적은 디스크 IO로 쿼리를 처리할 수 있다.
   >  인덱스 풀 스캔은 필요한 데이터만 인덱스에서 가져오기 때문입니다. 더불어서 풀스캔은 테이블의 모든 행을 검색하기 때문입니다. 
그러나 반대인 경우도 있습니다. 일반적인 DBMS 옵티마이저는 인덱스를 통해 레코드 1건을 읽는 것이 테이블에서 직접 레코드 1건을 읽는 것보다 4-5배 정도 비용이 더 많이 드는 작업으로 예측합니다.  그렇기에 인덱스를 통해 읽어야 되는 건수가 전체 테이블 레코드의 10-15%를 넘는다면, 인덱스를 사용하지 않고 테이블을 모두 직접 읽어서 필요한 레코드만 가려내는 필터링 방식으로 처리하는 것이 더 효율적입니다.

2. 칼럼 B가 인덱스가 걸려 있는데, 모든 B의 값이 동일한 경우 결국 다 찾는 행위가 될텐데, 이때도 효율적인가?
  > 거의 그럴 경우는 없겠지만 그렇다면 테이블 풀스캔이 더 효율적일 것입니다.
예를 들어보겠습니다.  칼럼 B가 boolean 타입이며, 모든 레코드가 true인 경우를 가정해 보겠습니다. 이 경우 인덱스 풀 스캔을 수행하면 인덱스의 리프노드에는 true 값을 가지는 모든 행의 주소값이 저장되어 있습니다. 그렇다면 테이블 풀스캔과 다를 바가 없습니다. 1번에서 말씀드렸듯이 기본 조회보다 인덱스를 사용하는 방식이 더 비용이 들어갑니다. 그렇기 때문에 예시와 같은 경우 테이블 풀스캔을 하는 것이 더 효율적인 방법이라고 생각할 수 있습니다.
